---
#项目名称
name: test
#项目生成文件输出目录
#output_dir:  "/Users/chunxiaoli/IdeaProjects/"
output_dir:  "./"
type: "rpc"
#maven groupId
group_id: "com.dafy.dev"
#dubbo rpc owner
owner: chuxniao

#json_file controller cgi protocol file
cgi_json_file: "app.json"

#logback config template
log_config_file: "logback.xml"


#application.properties template
application_properties_template_path: "application.properties"

#mybatis config
mybatis:
  host: "10.8.15.65"
  port: "3306"
  username: root
  password: "dafy1024"
  database: dafy_mall
  encoding: utf-8
  db_type:  "MySQL"
  tables:
          -   table_name: t_brand
              domain_name: Brand
